version: '2'
services:
    php:
        build: ./php
        container_name: php
        tty: true
        links:
          - mysql
        volumes:
          - ../:/www
        networks:
            - github-interaction

    mysql:
        image: mariadb
        environment:
          - MYSQL_ROOT_PASSWORD=123456
        tty: true
        container_name: mysql
        volumes:
          - ./data/mysql:/var/lib/mysql
        networks:
            - github-interaction

networks:
    github-interaction:
        external: true
